TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.13
  max_vel_theta: 0.3
  min_in_place_vel_theta: 0.15

  acc_lim_theta: 1.6
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  holonomic_robot: false
  
  xy_goal_tolerance:  0.25
  yaw_goal_tolerance: 0.25
  
  sim_time: 2.0
  
  dwa: true
  
  meter_scoring: true
