obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.15, 0.1], [-0.15, 0.1], [-0.15, -0.1], [0.15, -0.1]] 
robot_radius: 0.3 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.35
transform_tolerance: 2
controller_patience: 2.0

NavfnROS:
    allow_unknown: true
    track_unknown_space: true
     
observation_sources: point_cloud_sensor
# assuming receiving a cloud from rtabmap_ros/obstacles_detection node
point_cloud_sensor: {
  sensor_frame: base_link,
  data_type: PointCloud2,
  topic: /planner_cloud,
  marking: true,
  clearing: true,
  min_obstacle_height: -99999.0,
  max_obstacle_height: 99999.0}

